include::../attributes-sections.adoc[]
:sca: pass:c,q[`SmartcardArchive`]

== Smartcards-Brick

Smartcards mittels `smartcard-brick`.... TODO

[plantuml, "{pumldir}/smartcard-brick", svg]
.Smartcard-Brick
----
include::{pumldir}/smartcard-brick.puml[]
----

=== Smartcards

Die Smartcards sind folgendermaßen aufgebaut:

[plantuml, "{pumldir}/smartcards", svg]
.Smartcards
----
include::{pumldir}/smartcards.puml[]
----

=== Smartcard-Archiv
Das {sca} ist ein Archiv, in dem die Smartcards verwaltet werden.

[plantuml, "{pumldir}/smartcards-archive", svg]
.Smartcards
----
include::{pumldir}/smartcards-archive.puml[]
----

Bevor man das {sca} nutzen kann, muss dieses zunächst mit den gewünschten Smartcards initialisiert werden.
Hierfür hat man die Möglichkeit eigene Smartcards aus dem Dateisystem zu laden:

[#sca_file,java]
----
var smartcardsImage = new File("your/path/to/smartcards.json");
var sca = SmartcardArchive.from(smartcardsImage);
----

Alternativ ist es auch möglich, die Smartcard Images als Java-Resources (`resources/smartcards/smartcards.json`) zu speichern und diese dann folgendermaßen in das {sca} zu laden:

[#sca_resources,java]
----
var sca = SmartcardArchive.fromResources();
----

Anschließend können die Smartcards aus dem {sca} anhand unterschiedlicher Kriterien geladen werden:

[#sca_load_explicit_smartcards,java]
----
var egk0 = sca.getEgk(0);
var egk1 = sca.getEgkByICCSN("80276883110000113311");
var egk2 = sca.getEgkByKvnr("X110407071");

var hba0 = sca.getHba(0);
var hba1 = sca.getHbaByICCSN("80276001011699901501");

var smcb0 = sca.getSmcB(0);
var smcb1 = sca.getSmcBByICCSN("80276001011699900861");
----

Das {sca} bietet darüber hinaus auch die Möglichkeit eine Smartcard anhand des konkreten Typs und der ICCSN zu laden:

[#sca_load_typed_smartcards,java]
----
Egk egk1       = sca.getByICCSN(Egk.class, "80276883110000113311");
Smartcard egk2 = sca.getSmartcardByICCSN(SmartcardType.EGK, "80276883110000113311");

Hba hba1       = sca.getByICCSN(Hba.class, "80276001011699901501");
Smartcard hba2 = sca.getSmartcardByICCSN(SmartcardType.HBA, "80276001011699901501");

SmcB smcb0     = sca.getByICCSN(SmcB.class, "80276001011699900861");
Smartcard hba2 = sca.getSmartcardByICCSN(SmartcardType.SMC_B, "80276001011699900861");
----

NOTE: Bei dem Aufruf über `getSmartcardByICCSN` wird die Smartcard als Basis-Klasse `Smartcard` zurückgegeben, weil hier der konkrete Typ der Smartcard syntaktisch nicht bekannt ist. Es sollen, wenn immer möglich, die konkreten und typisierten Methoden verwendet werden umd die Typsicherheit zu bewahren.

Das {sca} kann natürlich aber nur Smartcards laden und herausgeben, die konfiguriert sind.
Das bedeutet, dass die folgenden beiden Aufrufe zur Laufzeit zu Fehlern führen:

[#sca_load_unknown_smartcards,java]
----
// exeeding index
assertThrows(IndexOutOfBoundsException.class, () -> sca.getEgk(100));

// unknown ICCSN
assertThrows(SmartcardNotFoundException.class, () -> sca.getEgkByICCSN("123"));
----

WARNING: Grundsätzlich wird dringend davon abgeraten, das Laden der Smartcards über den Index als Standardmethode zu verwenden.

Beide Fehlerfälle können zur Laufzeit in etwa folgendermaßen behandelt werden:

[#sca_load_unknown_smartcards_safely,java]
----
// gives you the amount of known EGK smartcards
int idx = 100;
int amountEgks = sca.getConfigsFor(SmartcardType.EGK).size();
if (amountEgks <= idx) {
    // do something about it
}

// gives you an empty optional because ICCSN "123" is unknown
Optional<Smartcard> opt = sca.getByICCSN("123");
if (opt.isEmpty()) {
    // do something about it
}
----
