include::attributes-settings.adoc[]

= B^2^ric^2^s
{author}
[VERSION], {docdate}
:toc: left
:docinfo: shared


== Scope
As a national competence center for digital health, {orgname} covers a broad spectrum of core areas of the German healthcare system. This includes the development of test suites, test tools and self-developed products for the digital health infrastructure.

Many products are built for TI, both inside and outside {orgname}. Redundant development is hard to avoid. However, the {bbriccs-wordmark} (`briks`) is trying to bundle many of the common solutions into a reusable SDK, which promises to significantly reduce development time and costs.

=== Acronym
While {bbriccs-wordmark} is just the word mark and is rather cumbersome in everyday use,
the following uses are recommended depending on the situation:

- Pronunciation: simply `briks` based on the idea clamping blocks
- Spelling: in the simplest case just `bricks` or `bbriccs` as a mnemonic for the word mark
- Code: the spelling `bbriccs` is only to be used for package names and namespaces, while `brick` (or `bricks` for plural) shall be used for variable, class or module names

include::bricks/index.adoc[leveloffset=+1]
