<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.gematik.bbriccs</groupId>
        <artifactId>fhir-bricks</artifactId>
        <version>0.12.1</version>
    </parent>

    <name>FHIR StructureMaps Transformation Brick</name>
    <description>Transformation Brick to create a resources using StructureMaps</description>
    <artifactId>fhir-smaps-transformation-brick</artifactId>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>2.4.20</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <jvmTarget>${kotlin.compiler.jvmTarget}</jvmTarget>
                            <jdkHome>${java.home}</jdkHome>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <jvmTarget>${kotlin.compiler.jvmTarget}</jvmTarget>
                            <jdkHome>${java.home}</jdkHome>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
              <dependencies>
                <dependency>
                  <groupId>org.jetbrains.kotlin</groupId>
                  <artifactId>kotlin-maven-lombok</artifactId>
                  <version>${kotlin.version}</version>
                </dependency>
              </dependencies>
              <configuration>
                <compilerPlugins>
                  <plugin>lombok</plugin>
                </compilerPlugins>
              </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.16.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <!-- Exclude HAPI FHIR classes that are too large for JaCoCo instrumentation -->
                        <exclude>org/hl7/fhir/**/*</exclude>
                        <exclude>ca/uhn/fhir/**/*</exclude>
                    </excludes>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <profiles>
        <profile>
            <id>publish</id>
            <build>
                <plugins>
                    <plugin>
                        <!-- maven-javadoc-plugin doesn't support kotlin code -->
                        <groupId>org.jetbrains.dokka</groupId>
                        <artifactId>dokka-maven-plugin</artifactId>
                        <version>2.2.0</version>
                        <executions>
                            <execution>
                                <id>javadocJar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>javadocJar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <sourceDirectories>
                                <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
                            </sourceDirectories>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>2.4.20</version>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>configuration-api-brick</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tools.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>resource-loader-brick</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>feature-toggle-brick</artifactId>
            <scope>test</scope>
        </dependency>


        <!-- required dependencies for HAPI FHIR FhirPatch -->
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-caching-caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-storage</artifactId>
            <exclusions>
                <!-- we need only FhirPatch functionality, skip the rest which we don't need -->
                <exclusion>
                    <groupId>ca.uhn.hapi.fhir</groupId>
                    <artifactId>hapi-fhir-jpaserver-searchparam</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ca.uhn.hapi.fhir</groupId>
                    <artifactId>hapi-fhir-jpa</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ca.uhn.hapi.fhir</groupId>
                    <artifactId>hapi-fhir-jpa-hibernate-services</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ca.uhn.hapi.fhir</groupId>
                    <artifactId>hapi-fhir-server</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>ca.uhn.hapi.fhir</groupId>
                    <artifactId>hapi-fhir-repositories</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate.search</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate.orm</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.hibernate.validator</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.data</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>jakarta.servlet</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.quartz-scheduler</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- this is required because we have excluded hapi-fhir-jpa -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>4.6.0</version>
        </dependency>
    </dependencies>

</project>