<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.gematik.bbriccs</groupId>
        <artifactId>fhir-bricks</artifactId>
        <version>0.12.1</version>
    </parent>

    <name>FHIR Comparator Brick</name>
    <description>Parent module for different FHIR Comparators</description>
    <artifactId>fhir-comparator-bricks</artifactId>

    <packaging>pom</packaging>
    <modules>
        <module>fhir-comparator-fhirpatch-brick</module>
        <module>fhir-comparator-jsondiff-brick</module>
        <module>fhir-comparator-api-brick</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>2.4.20</version>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>fhir-smaps-transformation-brick</artifactId>
            <version>0.12.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>fhir-smaps-transformation-brick</artifactId>
            <version>0.12.1</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>

        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>2.4.20</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>publish</id>
            <build>
                <plugins>
                    <plugin>
                        <!-- maven-javadoc-plugin doesn't support kotlin code -->
                        <groupId>org.jetbrains.dokka</groupId>
                        <artifactId>dokka-maven-plugin</artifactId>
                        <version>2.2.0</version>
                        <executions>
                            <execution>
                                <id>javadocJar</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>javadocJar</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <sourceDirectories>
                                <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
                            </sourceDirectories>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>