include::../attributes-sections.adoc[]

[#conf-feature-toggle-brick]
== Feature-Toggle
A feature toggle module allows developers to enable or disable certain functions or code sections in an application. This is particularly useful for the gradual introduction of new features. Especially in test suites, we often have the case that certain features go through different stages and need to be activated or deactivated in different environments.

The `feature-toggle-brick` offers a flexible solution by allowing functions to be enabled or disabled via system properties and environment variables.

[plantuml, "{pumldir}/feature-toggle-brick", svg]
.Feature-Toggle-Brick
----
include::{pumldir}/feature-toggle-overview.puml[]
----

To increase maintainability in the code, the `feature-toggle-brick` offers an abstraction with a simple API to read feature toggles from the system without directly accessing system properties or environment variables. This reduces the dependency on the respective "key" (whether it is a system property or an environment variable) to a minimum. It not only focuses on the abstraction of system properties/environment variables but also offers a concept to configure feature toggles simultaneously via system properties and environment variables.

.Use it when:
* You have many feature toggles in your application
* You have to use specific feature toggles in many different places of your code
* You need to use SystemProperties and EnvironmentVariables simultaneously to control your feature toggles

.Don't use it when:
* You have only a few feature toggles in your application and the `feature-toggle-brick` is not already in your classpath

include::tutorial-feature-toggle-create.adoc[leveloffset=+1]
include::tutorial-custom-feature-toggle.adoc[leveloffset=+1]

