@startuml
skinparam componentStyle rectangle
left to right direction

skinparam component {
    BackgroundColor<<external>> Yellow
    BorderColor<<external>> Red
}

node "Common Profiles" #D4DCFF {
    [fhir-ucum-brick]
    [fhir-de-basisprofil-r4-brick]
}

[epa-medication-brick] <<external>>

node "FHIR Facility" #FFD1E5 {
    [fhir-validation-brick]
    [fhir-codec-brick]
    [fhir-hapi-fuzzing-brick]
}

node "FHIR Core" #CCFFE0 {
    [fhir-configurator-brick]
    [fhir-coding-system-brick]
    [fhir-builder-brick]
}

[de.gematik.refv.referencevalidator-lib] <<external>>

[FHIR Facility] -up-> [FHIR Core]
[Common Profiles] -down-> [FHIR Core]
[epa-medication-brick] -right-> [FHIR Core]

[fhir-codec-brick] -left-> [fhir-validation-brick]
[fhir-coding-system-brick] -left-> [fhir-configurator-brick]
[fhir-validation-brick] -[#red,dashed]left-> [de.gematik.refv.referencevalidator-lib]
[fhir-validation-brick] -left-> [fhir-configurator-brick]
@enduml