@startuml
() "referencevalidator-lib" <<external>>
[x-fhir-bricks] <<external>>

node "FHIR Core" <<core>> {
    [fhir-ucum-brick] <<common>>
    [fhir-de-basisprofil-r4-brick] <<common>>
    [fhir-builder-brick] <<core>>
    [fhir-hapi-fuzzing-brick] <<core>>
    [fhir-configurator-brick] <<config>>
    [fhir-coding-system-brick] <<core>>
    [fhir-codec-brick] <<core>>
    [fhir-validation-brick] <<core>>

    [fhir-coding-system-brick] --> [fhir-configurator-brick] <<use>>
    [fhir-validation-brick] --> [fhir-configurator-brick] <<use>>
    [fhir-codec-brick] --> [fhir-validation-brick] <<use>>
    [fhir-codec-brick] --> [fhir-coding-system-brick] <<use>>
    [fhir-validation-brick] --> "referencevalidator-lib" <<decorate>>

    [x-fhir-bricks] --> [fhir-codec-brick] <<use>>
}
@enduml