@startuml

skinparam groupInheritance 2
skinparam packageStyle Frame
set namespaceSeparator none

interface ValidatorFhir {
    validate(content: String): ValidationResult
    validate(resource: Resource): ValidationResult
    isValid(content: String): boolean
    isValid(resource: Resource): boolean
}


class ProfiledValidator implements ValidatorFhir
class MultiProfiledValidator implements ValidatorFhir
class NonProfiledValidator implements ValidatorFhir
class ReferenzValidator implements ValidatorFhir
class DummyValidator implements ValidatorFhir

package de.gematik.refv {
    class ValidationModule
}

class ProfileExtractor {
    extractProfile(content: String): Optional<String>
    isUnprofiledSearchSet(content: String): boolean
}


MultiProfiledValidator *-left-> ProfiledValidator
MultiProfiledValidator -down-> ProfileExtractor
ReferenzValidator -[#red,dashed]down-> ValidationModule

@enduml