@startuml
interface HttpBClient
class BasicHttpClient

interface RequestHeaderProvider {
  + forRequest(HttpBRequest request): List<HttpHeader>
}

interface HttpBObserver {
  + onRequest(HttpBRequest request)
  + onResponse(HttpBResponse response)
}

class XRequestIdProvider {
  + forRequest(HttpBRequest request): List<HttpHeader>
}

BasicHttpClient .u.|> HttpBClient
BasicHttpClient *-l-> RequestHeaderProvider
BasicHttpClient *-r-> HttpBObserver
XRequestIdProvider .u.|> RequestHeaderProvider
@enduml