@startuml
node "RESTful Bricks" <<transport>> {
    [x-vau-client-brick] <<vau>>
    [rest-client-brick] <<transport>>
    [rest-client-api-brick] <<interface>>
    () "VAU" <<plugins>>
    () "REST" <<plugins>>

    [rest-client-api-brick] <|-down- [x-vau-client-brick] <<implement>>
    [rest-client-api-brick] <|-down- [rest-client-brick] <<implement>>
    [x-vau-client-brick] -> [rest-client-brick] <<decorate>>

    [x-vau-client-brick] -left-> "VAU" <<plugins>>
    [rest-client-brick] -right--> "REST" <<plugins>>
}

node "FHIR Client Brick" <<application>> {
    [fd-fhir-client-brick] <<application>>
    () "FHIR" <<plugins>>

    [fd-fhir-client-brick] -down--> [rest-client-api-brick] <<use>>
    [fd-fhir-client-brick] -left-> "FHIR Bricks" <<use>>
    [fd-fhir-client-brick] --> "FHIR" <<plugins>>
}

node "JSON Client Brick" <<application>> {
    [fd-json-client-brick] <<application>>
    [fasterxml] <<external>>

    [fd-json-client-brick] -down--> [rest-client-api-brick] <<use>>
    [fd-json-client-brick] -> [fasterxml] <<external>>
}
@enduml