@startuml
skinparam componentStyle rectangle

skinparam component {
    BorderColor<<fhir-bricks>> Red
    BorderStyle<<fhir-bricks>> Dashed
    BackgroundColor<<external>> Yellow
    BorderColor<<external>> Red
}

node "FHIR REST" #FFD1E5 {
    [fd-fhir-client-brick]
    [fhir-codec-brick] <<fhir-bricks>>
    [fhir-validation-brick] <<fhir-bricks>>
}

node "REST Communication" #D4DCFF {
    [rest-client-api-brick]
    [vau-client-brick]
    [rest-client-brick]
}


rectangle "FHIR REST Plugins" #CCFFE0 {
    () Header as RequestHeaderProvider
    [smartcard-idp-plugin-brick]
}
rectangle "VAU Plugins" #CCFFE0
rectangle "REST Plugins" #CCFFE0

[de.gematik.idp.idp-client] <<external>>

[fd-fhir-client-brick] -down--> [rest-client-api-brick] : uses
[fd-fhir-client-brick] -[#red,dashed]left-> [fhir-codec-brick] : uses
[fhir-codec-brick] -[#red,dashed]down-> [fhir-validation-brick] : uses

[fd-fhir-client-brick] -right-> [RequestHeaderProvider]

[vau-client-brick] -up-> [rest-client-api-brick] : implements
[rest-client-brick] -up-> [rest-client-api-brick] : implements

[vau-client-brick] -left-> [VAU Plugins]
[rest-client-api-brick] -right--> [REST Plugins]
[smartcard-idp-plugin-brick] -up-> [RequestHeaderProvider]

[smartcard-idp-plugin-brick] -[#red,dashed]right-> [de.gematik.idp.idp-client]
@enduml