@startuml
skinparam componentStyle rectangle

skinparam component {
    BackgroundColor<<external>> Yellow
    BorderColor<<external>> Red
    BackgroundColor<<p12>> #9397ab
}

[smartcard-cli-brick] #66FFA2

node "Smartcard-Brick" #D4DCFF {
    [SmartcardArchive]
    [Smartcard]
    [SmartcardCertificate]
    [X509Certificate] <<p12>>
}

[smartcard-cli-brick] -left-> [Smartcard-Brick] : "uses"
[SmartcardArchive] *-right-> [Smartcard]
[Smartcard] *-right-> [SmartcardCertificate]
[SmartcardCertificate] -down-> [X509Certificate]

@enduml