@startuml
set namespaceSeparator none

class SmartcardsArchive {
    smcbCache: List<SmcB>
    hbaCache: List<Hba>
    egkCache: List<Egk>
}

class SmartcardFactory {
    configs: List<SmartcardConfigDto>
}

SmartcardsArchive -> SmartcardFactory
SmartcardFactory o-right-> java.io.File

note bottom of SmartcardsArchive
    manages and caches
    the smartcards
end note

note bottom of SmartcardFactory
    creates smartcards
    and loads .p12 files
    based on the configs
end note
@enduml