@startuml
skinparam groupInheritance 2

abstract class Smartcard {
    iccsn: String
    certificates: List<SmartcardCertificate>
    getAutOids(): List<Oid>
}

abstract class InstituteSmartcard extends Smartcard{
    getTelematikId(): String
    getEncOid(): Oid
    getEncCertificate(CryptoSystem): SmartcardCertificate
}

class Egk extends Smartcard {
    getKvnr(): String
}
class Hba extends InstituteSmartcard
class SmcB extends InstituteSmartcard
enum SmartcardType {
    EGK
    HBA
    SMC_B
    SMC_KT
}


class SmartcardOwnerData {
    commonName: String
    title: String
    givenName: String
    surname: String
    organization: String
    organizationUnit: List<String>
    street: String
    locality: String
    postalCode: String
    country: String
}

Smartcard -left-> SmartcardType
Smartcard -right-> SmartcardOwnerData


@enduml