<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.gematik.bbriccs</groupId>
        <artifactId>utility-bricks</artifactId>
        <version>0.11.0</version>
    </parent>

    <artifactId>vsdm-check-digit-generator-brick</artifactId>
    <name>VSDM Check Digit Generator Brick</name>

    <dependencies>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>vsdm-check-digit-brick</artifactId>
        </dependency>
        <dependency>
            <groupId>de.gematik.bbriccs</groupId>
            <artifactId>smartcards-brick</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.ws</groupId>
            <artifactId>jakarta.xml.ws-api</artifactId>
            <version>${artefact.jakarta}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>${artefact.jakarta}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>jaxws-ri</artifactId>
            <version>${artefact.jakarta}</version>
            <type>pom</type>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>xjc.fa.vsds</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/resources/gematik_schemes/fa/vsds/Pruefungsnachweis.xsd</source>
                                <source>src/main/resources/gematik_schemes/fa/vsds/Schema_VSD.xsd</source>
                            </sources>
                            <outputDirectory>${project.build.directory}/generated/src/main/java</outputDirectory>
                            <clearOutputDir>false</clearOutputDir>
                            <packageName>de.gematik.ws.fa.vsds</packageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>